### ISSUE TITLE
Production install instructions for Ubuntu / Debian

### ISSUE THREAD

**Issue by ellisgeek** [fkooman/php-remote-storage#1]
I would love to see some instructions or at least a jumping off point for running this in "production" for Ubuntu / Debian and derivatives.

**Comment by omigeot** [comment]
I second that, especially on "hard" parts (oauth/webfinger).

**Comment by taophp** [comment]
+1

**Comment by skddc** [comment]
+1

Would also love to have a guide for Ubuntu. Posted a $100 bounty: https://www.bountysource.com/issues/5137137-production-install-instructions-for-ubuntu-debian

Even more awesome would be a .deb package in addition to the rpm one, of course.

**Comment by fkooman** [comment]
The installation itself is not so hard, for inspiration you can look at the Fedora installation instructions and deploy script as part of the deployment repository: https://github.com/fkooman/php-remote-storage-deployment/. I use it myself on the demo environment on https://storage.tuxed.net/.

You can also use the 'development' instructions in the updated README in this repository.

RPM spec files can be found here: https://github.com/fkooman/php-remote-storage-specs/.

**Comment by fkooman** [comment]
Not quite production instructions, but at least this goes a long way:

https://github.com/fkooman/php-remote-storage/blob/master/UBUNTU.md

**Comment by fkooman** [comment]
development intructions are now here: https://github.com/fkooman/php-remote-storage/blob/master/HACKING.md

**Comment by fkooman** [comment]
#24
