### ISSUE TITLE
tokens should expire at some point

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#12]
it may be a long time, but they should expire at some point. Maybe after 1 month by default?

**Comment by fkooman** [comment]
depends on fkooman/php-lib-oauth implement it

**Comment by fkooman** [comment]
we can easily implement this now as the OAuth server is included.

**Comment by benrubson** [comment]
Perhaps being able to choose the duration would be nice ?
Many thanks 👍

**Comment by fkooman** [comment]
I was thinking about 3 months by default, and indeed allow modifying it in the server configuration. Thoughts?

**Comment by benrubson** [comment]
Perfect 👍

**Comment by skddc** [comment]
Just FYI: we're about to launch something similar for 5apps Deploy, and the way we designed it is that you can use a dropdown menu to set the expiry time for a token in the auth dialog itself. The current options are "1 day", "1 month" and "never" for now, but it's subject to change based on real-world usage/testing.

**Comment by fkooman** [comment]
Ah that is clever! I could do something similar as well! I almost implemented the (admin) configurable expiry time, which is a good start I guess :)

**Comment by skddc** [comment]
This feature is now live on 5apps Storage. Check it out and let us know what you think!

**Comment by skddc** [comment]
I created https://community.remotestorage.io/t/expiring-rs-oauth-tokens/377 so other server developers and users can also find the conversation.

**Comment by fkooman** [comment]
They expire now (by default) after 90 days. Will look into allowing user to choose post 2.0.

**Comment by skddc** [comment]
Nice! (We also made token expiration a much nicer experience in the new rs.js connect widget).

So I guess this can be closed then, right?

**Comment by fkooman** [comment]
Well, the user cannot choose yet :-)

**Comment by skddc** [comment]
"tokens should expire at some point" is true now. :)

So I'd think of choosing as a new feature on top of that. No?

**Comment by fkooman** [comment]
Yes! :)
