### ISSUE TITLE
include WebFinger support directly in server

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#19]
add php-webfinger to php-remote-storage for easy accounts at storage server domain, no need to setup an additional php-webfinger service, too complicated.

**Comment by fkooman** [comment]
This was implemented. It is still hard/impossible to make this all work nicely integrated in the development environment. Works perfectly in Vagrant/Production deploy. URL rewriting for /.well-known/webfinger is a bit hard to get right in Apache unfortunately :(

**Comment by fkooman** [comment]
0d9adee17257f42712fa238d395a7b8df10a7551

**Comment by csbenz** [comment]
Hi,

I'm trying to use remoteStorage with Laverna but am getting issues with WebFinger. The directory `https://example.com/.well-known/webfinger` doesn't exist on my server.
Is this something I should be setting up myself? How can I do that?

**Comment by fkooman** [comment]
It is not a directory, but just a resource that requires some parameters, e.g.:

    $ curl https://storage.tuxed.net/.well-known/webfinger?resource=acct:fkooman@storage.tuxed.net

If you do that for your domain it should just work if you installed php-remote-storage in the root of the domain, if not you need to forward the request to the appropriate location...
