### ISSUE TITLE
figure out URI_ENCODE/DECODE

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#2]
in PHP-FPM the PATH_INFO remains URI_ENCODED. So we store them with %20 in the FS if there is a space in the name and also show them in folder listings encoded. I am not sure this is correct behavior?

Also sync with specification...

**Comment by skddc** [comment]
Not sure. Just know that Liquor Cabinet doesn't deliver encoded filenames in folder listings. I think we handle both encoded and non-encoded keys and then deliver non-encoded ones in listings.

**Comment by fkooman** [comment]
https://github.com/remotestorage/spec/issues/103

**Comment by fkooman** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=55329

**Comment by fkooman** [comment]
https://github.com/fkooman/php-lib-http/commit/39a6d8e87e9c7571b2a740942fa3d105a05e3eff

**Comment by fkooman** [comment]
See #8
