### ISSUE TITLE
non RS API endpoint should not have CORS

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#21]
currently it seems all pages have CORS, that is not needed, only the remoteStorage API (and WebFinger) should have CORS.

**Comment by fkooman** [comment]
possibly also a security issue

**Comment by untitaker** [comment]
I'm not exactly sure if it's possible to do CSRF with this, but probably not. What you *can* do, however, is detecting which other apps the user has authorized, which is a privacy issue.
