### ISSUE TITLE
Preventing clickjacking during OAuth

### ISSUE THREAD

**Issue by untitaker** [fkooman/php-remote-storage#22]
See https://github.com/untitaker/mysteryshack/issues/10

Setting `X-Frame-Options` for admin and login area is probably sufficient, but I threw in a JS solution just because I can too.

**Comment by fkooman** [comment]
using JS to prevent security issues is kinda like... counter intuitive... in order to solve a problem you need to get more of the problem :)

**Comment by fkooman** [comment]
I am quite happy being completely JS-free :)

**Comment by fkooman** [comment]
Currently I'm using this:
```
X-Frame-Options: DENY
Content-Security-Policy: default-src 'self'
```

**Comment by untitaker** [comment]
Right, the issue is that currently those headers don't seem to be set.

**Comment by fkooman** [comment]
Huh? Are you sure? Hmm maybe only for the OAuth stuff, not for the login page?

**Comment by untitaker** [comment]
Nowhere really. At least the Firefox dev console doesn't show it?

**Comment by fkooman** [comment]
curl -i http://localhost:8080/_account does show it?

**Comment by untitaker** [comment]
Ah yes, yikes. Weird.

**Comment by fkooman** [comment]
Hm.. it seems the response to the POST when authorizing an app does not have those headers... is that important?

**Comment by untitaker** [comment]
I'd just add that header to all requests (except maybe storage data) in one place. Not sure if there's something like a post-processing hook in your framework?

**Comment by fkooman** [comment]
Yup there is, but I think this particular one comes from the OAuth library... will have to investigate further. Thanks for reporting!

**Comment by fkooman** [comment]
https://github.com/fkooman/php-lib-oauth/commit/a7acb8c77fb7359ce6a23b140258daf587baac4e

**Comment by fkooman** [comment]
They are now set when loading the login page, and when loading the authorize page. That should be sufficient I guess :) It doesn't make sense to set those on redirect responses...
