### ISSUE TITLE
rename the project?

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#28]
it seems the name "Phorage" is acceptable.

**Comment by fkooman** [comment]
@michielbdejong suggested KooRS

**Comment by michielbdejong** [comment]
Or Françtore :)

**Comment by fkooman** [comment]
KoRS

**Comment by fkooman** [comment]
Corpse

**Comment by fkooman** [comment]
Korps

**Comment by skddc** [comment]
I do like KORS a lot! :)

**Comment by skddc** [comment]
MARS. (Mah RS ;)).

**Comment by fkooman** [comment]
I also kinda like it actually thinking a bit more about it. So KORS with all caps?

**Comment by skddc** [comment]
Or Koors, for the beer hipsters to hate on. :)

**Comment by fkooman** [comment]
Only if we also steal the Coors logo and substitute the C :-)

**Comment by skddc** [comment]
http://www.dafont.com/team-spirit.font?text=Koors&psize=l

**Comment by fkooman** [comment]
I guess this ship has sailed, we can still rename it at some point, but for now it seems fine like this :)
