### ISSUE TITLE
use client_id to identify clients

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#3]

**Comment by fkooman** [comment]
https://github.com/remotestorage/spec/issues/101

**Comment by fkooman** [comment]
I'd be leaning towards using the `client_id` as the identifier, extracting the domain (host), making sure it matches the host of the `redirect_uri` and the the host to the user in the authorize dialog and approval management page.

**Comment by fkooman** [comment]
Currently there is NO requirement for `client_id` and `redirect_uri` to share the same domain.

**Comment by fkooman** [comment]
Done.

`redirect_uri` MUST be a valid URL, and `redirect_uri` MUST start with the value of `client_id` (`strpos`)

**Comment by untitaker** [comment]
>redirect_uri MUST start with the value of client_id

This, or the other way around?
