### ISSUE TITLE
debian doc - details the composer part

### ISSUE THREAD

**Issue by pierreozoux** [fkooman/php-remote-storage#34]
I tried to follow debian instructions, I was missing the composer part :)

I know it is obvious for php developer :)

And also, there is php5-mbstring dependency missing in the doc.

**Comment by fkooman** [comment]
Ah, on Ubuntu 14.04 you don't need the php5-mbstring dependency, on Fedora you do. Which version of Debian are you using?

Actually, composer is not needed for the server install (https://github.com/fkooman/php-remote-storage/blob/master/SERVER.md), only for developing the server itself (https://github.com/fkooman/php-remote-storage/blob/master/HACKING.md).

**Comment by pierreozoux** [comment]
for mbstring, I'm using [debian-jessie](https://github.com/docker-library/php/blob/master/5.6/apache/Dockerfile#L1) but yeah, sorry, I didn't see that the doc is just for ubunut14.04.

For composer, I got an error saying vendor was not found, but I actually just tested it, and you are right, composer is not needed :)

I'll close the issue.

**Comment by stueja** [comment]
Following the instructions in SERVER.md on a Debian system with the cloned github repo fails for me: `sudo bin/add-user username password` results in
```
PHP Warning:  require_once(/var/www/php-remote-storage/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/php-remote-storage/bin/add-user on line 4
PHP Fatal error:  require_once(): Failed opening required '/var/www/php-remote-storage/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/php-remote-storage/bin/add-user on line 4
```
So it seems that composer is needed. Or am I doing something wrong here?

**Comment by fkooman** [comment]
Composer should not be needed.

The instructions assume php-remote-storage is installed in `/var/www/php-remote-storage`, is that path actually available?

**Comment by stueja** [comment]
Oh, thank you for your quick answer.
Yes, it is installed in /var/www/php-remote-storage: 
```
root@router ~www # ls -al /var/www/
total 36368
drwxr-xr-x  9 www-data www-data     4096 Jun 26 12:01 .
drwxr-xr-x 12 root     root         4096 Jun  3 07:58 ..
lrwxrwxrwx  1 www-data www-data       31 Jun 12 07:40 dnsmasq.leases.txt -> /var/lib/dnsmasq/dnsmasq.leases
drwxr-xr-x  2 www-data www-data     4096 Jun  3 07:58 html
-rw-r--r--  1 root     root     37202740 May 31 22:09 latest-v2-package
drwxr-xr-x  9 www-data www-data     4096 Jun 26 12:01 laverna
drwxr-xr-x 12 www-data www-data     4096 Jun 26 08:11 php-remote-storage
drwxr-xr-x  4 www-data www-data     4096 Jun 12 17:16 rainloop
drwxr-xr-x 10 www-data www-data     4096 Jun 25 17:38 sc
drwxr-xr-x  4 ftpuser  ftpuser      4096 Jun 25 07:39 upload
lrwxrwxrwx  1 root     root           21 Jun 17 08:35 w -> /var/www/wallabag/web
drwxr-xr-x 12 www-data www-data     4096 May 31 21:56 wallabag
```
Unfortunately:
```
root@router ~www # ls -al php-remote-storage/vendor
ls: cannot access php-remote-storage/vendor: No such file or directory
```

**Comment by fkooman** [comment]
are you sure you took the release tarball as found on https://github.com/fkooman/php-remote-storage/releases, the `php-remote-storage-1.0.3.tar.xz` file? The .zip and .tar.gz are autogenerated by GitHub and don't contain the dependencies in the `vendor` directory.

**Comment by stueja** [comment]
Aha, no, I used `git clone` -- I will try again with the tarball later/tomorrow and let you know. Thank alot!

**Comment by stueja** [comment]
Thank you, that worked, I could add a user. Since I am using nginx, I am getting a lot of errors. I will try on.
