### ISSUE TITLE
Crypto signing releases

### ISSUE THREAD

**Issue by pierreozoux** [fkooman/php-remote-storage#35]
Do you plan to sign packages listed on https://storage.tuxed.net/fkooman/public/upload/php-remote-storage/releases.html with your public key?

**Comment by fkooman** [comment]
Yes that is the plan! :)

**Comment by pierreozoux** [comment]
nice! because it is kind of requirement for docker library official images

On 07-12-2015 17:51, François Kooman wrote:
> Yes that is the plan! :)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/fkooman/php-remote-storage/issues/35#issuecomment-162606225
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by fkooman** [comment]
That's ironic! Docker and signatures? :D 

Is there a link I should read up on? Or is it any kind of signature is fine?

**Comment by pierreozoux** [comment]
What do you mean that it is ironic?

You can get inspiration from ownCloud image for instance:
https://github.com/docker-library/owncloud/blob/master/8.1/fpm/Dockerfile#L43-L45

**Comment by fkooman** [comment]
The ironic part refers to the unsigned Docker images that everyone was downloading for the longest time, maybe that is fixed by now. 

I'll take a look at it, thanks! I did this kind of signatures before on other software as far as I can see from a quick glance :)

**Comment by fkooman** [comment]
I think I found how to do it more or less:

```
[fkooman@franet release]$ gpg -a -b --sign php-remote-storage-0.9.8.tar.xz 

You need a passphrase to unlock the secret key for
user: "François Kooman <fkooman@tuxed.net>"
4096-bit RSA key, ID 0x9C5EDD645A571EB2, created 2013-12-30

gpg: gpg-agent is not available in this session
[fkooman@franet release]$ cat php-remote-storage-0.9.8.tar.xz.asc
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQJ8BAABCgBmBQJWZpxsXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ2MjM3QkFGMTQxOEE5MDdEQUE5OEVBQTc5
QzVFREQ2NDVBNTcxRUIyAAoJEJxe3WRaVx6yXDgQAKBEzIvdf2cLmNTf29t/me9R
pA+qZTXvXcPTdRulHpG1Ped7BmO9/fvRse6kNaktlu32CFFR66D94oRa5jsh8bgV
iMIkun3bbfqD1rKDxpWR4MKQ8UOjZIpo5a6jwL76SPyI7MpPlVLOxMiDZdE47p9q
F3jP5OSs1E9Zb20PQrvxIOsScVLpJiatRH613mcWhNMYwoETrp7HlgUr3+d8B04w
SfxmjH2/Y2G8Z5C23YixwwvYU9Y5CkuWNEma5gWFSFcmwdwk1C6WrOICIn1i42WT
/a0V8widbXGVicQ4b1p3vmKRpwbQo3WKNVpeSTDtDI2aoteWbIND3zlCNndPYS4a
58dTmAodK+5zEFY/ADaywluJbKvgOHHpa940BX53dKM0Uw4yC0iW/lwuwgu1+xQA
08WP9KGs3TWUt7gzYGkWoEmI6ozY+zrkDkrinGggradKhaL9WzPrzmyGNcKT3wEp
dzVri/QtSfqdffHgg6nuaG7oEfBJDjHO39h4Q4/Xi5TqGrvxkERR5ibzspH1iEp+
ycLi1dZ8dBVvU/XzumD93groZi+k+W5vUzveRZ/KE9owgFnzH3roaBw2ozTYk1q9
tryQPKOPWcXUtS6uY3rMV6/caD9BIBi8jeP02yEcdWTd004mAObMy3VN5Cn/Rvw1
1qxkp9/korWyvvemARYN
=xhzU
-----END PGP SIGNATURE-----
[fkooman@franet release]$ gpg --verify php-remote-storage-0.9.8.tar.xz.asc
gpg: assuming signed data in `php-remote-storage-0.9.8.tar.xz'
gpg: Signature made Tue 08 Dec 2015 10:01:32 AM CET
gpg:                using RSA key 0x9C5EDD645A571EB2
gpg: Good signature from "François Kooman <fkooman@tuxed.net>" [ultimate]
[fkooman@franet release]$ 
```

**Comment by fkooman** [comment]
https://storage.tuxed.net/fkooman/public/upload/php-remote-storage/releases.html

**Comment by pierreozoux** [comment]
Yes, docker images are now signed :)

Looks good to me, I'll set it up!
