### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by skddc** [fkooman/php-remote-storage#38]
I just saw that the 1.0 milestone is at 100% here. Anything missing for a 1.0 release tag?

**Comment by fkooman** [comment]
I am basically waiting for @pierreozoux, there were still some issue with Docker, see #36. If all works for him I can release :)

**Comment by fkooman** [comment]
Oh, and the name... maybe leaving it php-remote-storage is not such a bad idea :)

**Comment by skddc** [comment]
> I am basically waiting for @pierreozoux, there were still some issue with Docker, see #36. If all works for him I can release :)

Ah, yes. Good idea.

> Oh, and the name... maybe leaving it php-remote-storage is not such a bad idea :)

The only thing I can say is that "Phorage" hasn't inspired feelings of love in everyone I told it. :)

**Comment by fkooman** [comment]
The other names, see #28 are also not "perfect"...

**Comment by pierreozoux** [comment]
IMHO the name is perfect! All the other name are confusing.

For the Dockerfile, it is now working. You can find instructions [here](https://github.com/indiehosters/remoteStorage). Do you want me to PR here?

**Comment by fkooman** [comment]
@pierreozoux you mean php-remote-storage is perfect? :)

**Comment by fkooman** [comment]
0.9.9 was released based on testing by @pierreozoux and it works now for IndieHosters! I also did some basic testing on https://rs.indie.host/ and it works fine!

**Comment by fkooman** [comment]
@pierreozoux I have the repository (https://github.com/fkooman/php-remote-storage-deployment) also, maybe a PR makes sense there, not here... 

but as-is the Docker image only works in *development* mode, as HTTPS is required for the session cookies. You need a HTTPS (proxy) in front of it.

**Comment by pierreozoux** [comment]
Yes, I like the name like this (but you know, tastes...).
Ok. I'll PR there.

**Comment by fkooman** [comment]
Released!

**Comment by skddc** [comment]
![dancing](https://cloud.githubusercontent.com/assets/842/11913924/ee1dd9aa-a641-11e5-9000-0186bded78b9.gif)
