### ISSUE TITLE
404 not found _account

### ISSUE THREAD

**Issue by MatthieuScarset** [fkooman/php-remote-storage#41]
Hi ! 
First of all, thank you for such a great project.
I've clone it and i've managed to install everything.
I have the web interface correclty working over https.

However, I can't go any further.
I got 404 not found as soon I try to sign in.

Do you have any idea why I'm having this issue ?

FYI here's my VHost conf:
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerAdmin me@me.com
        ServerName remote.dev

        DocumentRoot /path/to/remote-server/web
        <Directory /path/to/remote-server/web>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error-remote-server.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/ssl_access-remote-server.log combined

        #   SSL Engine Switch:
        SSLEngine on
        SSLCertificateFile    /path/to/my-ssl-cert.pem
        SSLCertificateKeyFile /path/to/my-ssl-cert.key

        #SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>

        BrowserMatch "MSIE [2-6]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0
        # MSIE 7 and newer should be able to use keepalive
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
</VirtualHost>
</IfModule>

**Comment by MatthieuScarset** [comment]
oups! Sorry...

I just found out that there is an example config file under contrib/storage.local.conf

It's all Ok now !

See ya!

**Comment by fkooman** [comment]
Hey, thanks for testing it! Did you read https://github.com/fkooman/php-remote-storage/blob/master/SERVER.md by any chance? Maybe I can improve the documentation if something was unclear! Thanks!
