### ISSUE TITLE
apache2 xsendfile and.. browsers.

### ISSUE THREAD

**Issue by xcasex** [fkooman/php-remote-storage#43]
so i'm having a fun time with firefox 44 & 45 along with chrome-stable linux 32bit, 64bit version on linux is the one that works as expected.

issue is as follows:
firefox results in a xsendfile module error 
`[Sat Apr 02 02:31:39.710071 2016] [:error] [pid 11778] (20023)The given path was above the root path: [client 192.168.2.130:59632] xsendfile: unable to find file: /var/www/html/php-remote-storage/data/storage/case/documents/notes/62D1A08C-CF10-4640-ACA5-623C70ECED80, referer: http://192.168.2.124:8000/`
aside from the php code using the old but deprecated "sendfile on" directive along with the new xsendfilepath, im at a serious loss here.

so the login process is broken as well.

chrome-stable 32bit on linux, results in the javascript console being spammed with cors issues, been trying some different header foo to no avail. although i can log onto the remote storage server, authenticate but there it stops, spamming the console with the above mentioned cors issue/s.

anyone else run into this?

**Comment by fkooman** [comment]
Did you follow the instructions here: https://github.com/fkooman/php-remote-storage/blob/master/SERVER.md? There are specific instructions for Debian/Ubuntu. If so, then I guess I screwed up somewhere in those instructions...

"SendFile on" is to make Apache send the data directly to the web browser (using `mod_xsendfile`), not going through PHP anymore which is more efficient and allows for HTTP range requests etc.

**Comment by xcasex** [comment]
I did indeed, like i mentioned, i have it working with chrome 64 bit, which is why this is an odd edgecase.

Ah, i mightve misread then.

**Comment by fkooman** [comment]
I don't understand what the edge case is and why "64 bit" makes any difference? It doesn't make any sense.

**Comment by fkooman** [comment]
Can you describe all the steps you took? The version of the OS? I assumed it was Debian or Ubuntu? The browser? What is going on with your browser? You compiled it yourself? Some special build? Do you have issues with the official Firefox and Chrome browser?

**Comment by xcasex** [comment]
steps as per the server.md 
the os's are: fedora, ubuntu 15.04 & debian jessie all running in separate lxc containers, certificates are from lets encrypt.

the firefox builds are from distribution repositories ('cept for firefox 45 which was downloaded from moz.org), chrome are from the official chrome repositories. 

and no, no issues with official builds, less problems that way.

**Comment by fkooman** [comment]
`unable to find file: /var/www/html/php-remote-storage`

This is not according to the instructions, did you really install it in the `html` folder? Then you also need to update the Apache config I guess... See the examples in the `contrib` directory.

**Comment by xcasex** [comment]
Indeed, i have a different root on /that/ singular server and have also tried it as per your guide. 

But going from your replies,  we'll be using another solution. 

Thank you for your effort.
