### ISSUE TITLE
xxx_client_should_set_state_xxx with laverna

### ISSUE THREAD

**Issue by stueja** [fkooman/php-remote-storage#46]
I am trying to use php-remote-storage together with [laverna](http://laverna.cc) on my own web server (nginx on debian-ish) at home.
Whenever I hit "Connect to remote storage" and login, I will be redirected to http://my.laverna.local/#xxx_client_should_set_state_xxx.
I used `grep -r xxx_client_should_set_state_xxx /var/www/php-remote-storage` and found it in `/php-remote-storage/vendor/fkooman/oauth/src/fkooman/OAuth/RequestValidation.php`.
Also, whatever I do, I cannot recall my saved notebooks. I can see them in `/var/www/php-remote-storage/data/storage/username/laverna/notes-db/`, but they are not visible in the web app.

My question: are those two behaviors (xxx_client...) and (can't load notes) interconnected? And if so, what can I or should laverna (or you? ;) ) do to resolve this?

Thanks alot,
Jan

**Comment by fkooman** [comment]
Heya,

No they are not related. Probably there is a CORS issue with that? 

The complaint about the `state` parameter is an issue where the client (in this case remotestorage.js/laverna) SHOULD send and validate the `state` parameter to mitigate CSRF. 

It should not influence functionality, it is a security issue.

**Comment by stueja** [comment]
Thank you; I specifically enabled CORS in the nginx config for laverna and php-remote-storage, but to no avail until now. I filed an issue with the laverna guys round the corner. ;)

**Comment by BenoitDuffez** [comment]
@stueja what's the issue number on their bug tracker? Couldn't find it by searching for `xxx_client_should_set_state_xxx`.

**Comment by fkooman** [comment]
the issue with showing `xxx_client_should_set_state_xxx` is fixed in master. In the future it will not complain anymore about the missing state parameter.

**Comment by anmol26s** [comment]
I even can not recall my notes. The notes files are empty but are present in the server.
@stueja Were you able to fix it?

**Comment by stueja** [comment]
@anmol26s No, sorry, weren't able and haven't cared for this issue since. Use another product to store notes.

**Comment by anmol26s** [comment]
@fkooman Please re-open the issue as I have tried it with other apps and this issue prevails with all of them.

**Comment by fkooman** [comment]
This is purely cosmetic, it doesn't affect any functionality.
