### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by j0nr** [fkooman/php-remote-storage#47]
I am just trying to get this setup. I get to the landing page, press "sign in" and then I get a 404 Not Found page. Its trying to find "_account" but cannot.

**Comment by fkooman** [comment]
Did you follow these instructions: https://github.com/fkooman/php-remote-storage/blob/master/SERVER.md?

If you are using nginx, see this issue: https://github.com/fkooman/php-remote-storage/issues/44

If it doesn't help, let me know :)

**Comment by j0nr** [comment]
Hi, 

Yes I followed those instructions, for Ubuntu and I use Apache2 . 

Thanks for quick response

**Comment by fkooman** [comment]
What version of Ubuntu? 14.04 or 16.04?

**Comment by j0nr** [comment]
Sorry, 14.04 and Apache 2.4.7

**Comment by fkooman** [comment]
I'll have to look into it then, I didn't try this for a while on Debian/Ubuntu :)

**Comment by j0nr** [comment]
Hi, 

Any joy with this? 

Thanks.

**Comment by fkooman** [comment]
I just installed it on Ubuntu 14.04 LTS with all updates installed and it works. A couple of things maybe not obvious from the SERVER.md:

1. the hosts file you modify on your own machine, not on the server where you try to install php-remote-storage
2. did you update the host name in the apache config file /etc/apache2/sites-available/storage.local.conf (or however you named the host)? you also need to modify the hostname *inside* this config file to match your own
3. did you use version 1.0.4? Or which version did you use?

**Comment by j0nr** [comment]
Hi, 

1. That was understood

2. Yes all modified to suit my naming

3. I have 1.0.3. I will try updating to 1.0.4

Thanks for now

**Comment by j0nr** [comment]
OK... Now I put 1.0.4 on and it seems to be working. Well 'll I can get to the login screen now. 

Thanks! 

Just a bit confused about how setting up a user works? Is it any Unix account in the system?

**Comment by fkooman** [comment]
Great!

No, it stores the user accounts in `config/server.yaml`. You can use the provided script to add the users.

**Comment by j0nr** [comment]
Excellent! All working, many thanks for your help.

Jon

**Comment by fkooman** [comment]
What I am still curious about is why it works with 1.0.4 and not with 1.0.3, there is only a very small fix that seems unrelated to your issues... are you sure you had 1.0.3 before?

**Comment by j0nr** [comment]
If only I knew :) 

I don't know whether there was some other factor (maybe my lack of skills?!).

**Comment by j0nr** [comment]
Hmm... sorry if wrong place, but the main reason I set this up (well initially) was to use [Laverna](https://laverna.cc/).  When I try and connect to my remote storage I get a load of errors shown in the screenshot of Chrome dev console. Any ideas which side (laverna or php-remote-storage) is causing this and how to rectify?

The odd thing is that it works when used on my phone! (Android, Chrome)

![lav_concole](https://cloud.githubusercontent.com/assets/2248120/17779340/4014447e-655f-11e6-900b-5097430d839e.PNG)

**Comment by fkooman** [comment]
It seems you are missing CORS headers on your server? That is strange!

```
[fkooman@fralen vpn-admin-portal]$ curl -i https://storage.tuxed.net/.well-known/webfinger?resource=acct:fkooman@storage.tuxed.net
HTTP/1.1 200 OK
Date: Fri, 19 Aug 2016 10:43:23 GMT
Server: Apache
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=15768000
Content-Length: 895
Content-Type: application/jrd+json

[snip]
```

**Comment by j0nr** [comment]
Well, after a quick Google, I added this within the <directory> section in the remote-storage apache conf file

    Header set Access-Control-Allow-Origin "*"

And that made it work on my phone, but on desktop for whatever reason. I don't really know much about CORS...is there some other setting I should try? This is just a standard apache2 install.

**Comment by j0nr** [comment]
curl -i https://storage.example.org/.well-known/webfinger?resource=acct:jonr@storage.example.org
    curl: (60) SSL certificate problem: self signed certificate

Could this be a problem?

**Comment by fkooman** [comment]
You do not need to modify the Apache configuration. The PHP code does that already.

The app on Android probably works because it is not using the browser, so it does not need CORS? 

Yes, you need to first accept the self signed certificate in your browser before it can work...

**Comment by j0nr** [comment]
>You do not need to modify the Apache configuration. The PHP code does that already.

OK, but before I did that it did not work on Android Chrome Browser.


>The app on Android probably works because it is not using the browser, so it does not need CORS?

Its not an app, its just in Google Chrome browser for Android.


>Yes, you need to first accept the self signed certificate in your browser before it can work...

From within the Laverna interface, there is no option to do this. When browsing to the installation of php-remote-storgae, then yes, I accept the cert. and it works.

**Comment by fkooman** [comment]
So it works now? :)

**Comment by j0nr** [comment]
No, it only works on my Android Chrome Browser. NOT on desktop Chrome or Firefox.

**Comment by fkooman** [comment]
You are sure you acepted the certificate there as well? you can browse to the storage server directly without certificate error? the CORS headers are sent back? Did you verify with curl like I did in the previous message?

**Comment by j0nr** [comment]
Right, I see what is happening (I think).  I had not previously browsed to  my php-remote-storage page in desktop browser, to let me accept certificate. Once I did that, then went back to Laverna, I could connect!

Although...the notes I made in Laverna on my phone are not visible when I log in via desktop...but I guess that's an issue for them, not you :)

Many thanks for your perseverance.

**Comment by fkooman** [comment]
You could try with sharesome, https://sharesome.5apps.com/ it is really nice for testing.

**Comment by j0nr** [comment]
That's very cool! Thanks! An easy way to host from your own remoteStorage :)

**Comment by fkooman** [comment]
exactly :)
