### ISSUE TITLE
Bad Request (invalid redirectUrl) with nginx, laverna.cc

### ISSUE THREAD

**Issue by guillaume-uH57J9** [fkooman/php-remote-storage#48]
Application : Laverna 0.7.4 rc4 https://github.com/Laverna/laverna/releases/tag/0.7.4-RC1
Application OS: Android Cyanogenmod
Web server: nginx-full 1.6.2-5+deb8u2+b1
Web service OS: Debian 8.5

Laverna is an application (web, android) for note keeping that support multiple storage backends, including remote-storage. 

Upon oauth authentication, when submitting the login/pass pair, the next page displayed is a "Bad Request / Invalid redirectUrl" error. 

Relevant web logs: 

```
RE.DA.C.TED - - [07/Aug/2016:19:27:03 +0200] "POST /_auth/form/verify HTTP/1.1" 302 5 "https://storage.REDACTED/_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&response_type=token" "Mozilla/5.0 (Linux; Android 5.1.1; XT1092 Build/LMY48Y) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36"
RE.DA.C.TED - - [07/Aug/2016:19:27:03 +0200] "GET /_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&response_type=token HTTP/1.1" 400 152 "https://storage.REDACTED/_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&response_type=token" "Mozilla/5.0 (Linux; Android 5.1.1; XT1092 Build/LMY48Y) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36"
```

**Comment by guillaume-uH57J9** [comment]
Note this error is only seen with the Laverna Android app.

It works fine with the Laverna.cc web app on my Desktop with Firefox (just tested it again). 

Here are web server logs showing a successful logon+redirect : 

```
192.168.REDA.CTED - - [07/Aug/2016:19:41:41 +0200] "POST /_auth/form/verify HTTP/1.1" 302 5 "https://storage.REDACTED/_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc%2Fapp%2F&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&state=notes&response_type=token" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
192.168.REDA.CTED - - [07/Aug/2016:19:41:41 +0200] "GET /_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc%2Fapp%2F&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&state=notes&response_type=token HTTP/1.1" 302 5 "https://storage.REDACTED/_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc%2Fapp%2F&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&state=notes&response_type=token" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
```

**Comment by guillaume-uH57J9** [comment]
To see if this is related to the browser (Chrome) that the Android app uses, I've tested again using Laverna.cc web app and Chromium. 

There's no BadRequest error, but the redirection seems incomplete as I land on the following page, which result in the application not loading : 
https://laverna.cc/app/#xxx_client_should_set_state_xxx

```
192.168.REDA.CTED - - [07/Aug/2016:19:46:41 +0200] "POST /_auth/form/verify HTTP/1.1" 302 5 "https://storage.REDACTED/_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc%2Fapp%2F&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&response_type=token" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
192.168.REDA.CTED - - [07/Aug/2016:19:46:41 +0200] "GET /_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc%2Fapp%2F&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&response_type=token HTTP/1.1" 302 5 "https://storage.REDACTED/_oauth/authorize?login_hint=guillaume&redirect_uri=https%3A%2F%2Flaverna.cc%2Fapp%2F&scope=laverna%3Arw&client_id=https%3A%2F%2Flaverna.cc&response_type=token" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"
```

**Comment by fkooman** [comment]
I just tested it on Google Chrome (google-chrome-stable-52.0.2743.116-1.x86_64) and it works fine there with my storage server (https://storage.tuxed.net/) running php-remote-storage.

**Comment by guillaume-uH57J9** [comment]
Your server's header show it is running Apache, so this *could* be specific to nginx. 

I have followed the template configuration described in #44

**Comment by fkooman** [comment]
Other apps do work? See e.g. https://wiki.remotestorage.io/Apps for a list...

**Comment by guillaume-uH57J9** [comment]
I've reproduced the main issue (Bad Request) only with Laverna's Android App so far. 
The remotestorage wiki lists various web/Firefox/Chrome apps, but no Android app. 

The second issue involving #xxx_client_should_set_state_xxx but no Bad Request can be reproduce with the Laverna web app, but not with Litewrite web app. 
Upon careful observation of Chrome's address bar when testing Litewrite, #xxx_client_should_set_state_xxx does appear for a short momen, and is then replaced (presumably for the app). 

Because of this, I suspect the second issue is a problem with Laverna itself. 
If you agree, let's focus on the main issue (Bad Request) since it is a server-side issue, not a client issue. And php-remote-storage is the server application here.

**Comment by fkooman** [comment]
Ah I read now you are getting an "invalid redirect_uri". 

https://github.com/fkooman/php-lib-oauth/blob/413f510ad55dea7c0f64543561cbfc04ee44bd81/src/fkooman/OAuth/InputValidation.php#L59

It seems this is because the `redirect_uri` does not end with a `/`, it does not have a "path" defined. It was never an issue before, I think everyone always used the `/`, for sure remotestorage.js did. 

Technically my server violates the OAuth 2.0 specification it seems!

**Comment by fkooman** [comment]
since when does GitHub auto close issues? Aargh! I only want to close it when you confirm it fixed :-)

**Comment by fkooman** [comment]
I released 1.0.4 now that should solve your issue!

**Comment by guillaume-uH57J9** [comment]
This fixes the BadRequest issue when connecting with Laverna.cc android app :)
Feel free to close this. 

I've encountered other issues with the Laverna.cc android apps, but those appears to be application issues (which is understandable since it's their very first release). I may need to contact them on github.

**Comment by fkooman** [comment]
Thanks! Let me know if you find other issues in php-remote-storage :-) Good luck!
