### ISSUE TITLE
Bad Request - HTTP_REFERER header missing

### ISSUE THREAD

**Issue by j75** [fkooman/php-remote-storage#51]
Hello,

I have installed version 1.0.4 on a Debian Jessie (on Apache) , and after trying to log in I've got a page claiming 
> Bad Request 
> HTTP_REFERER header missing

The only error displayed in Apache's error file is 
> AH02031: Hostname...  provided via SNI, but no hostname provided in HTTP request

**Comment by fkooman** [comment]
did you modify your browser settings not to send HTTP referrers?

**Comment by fkooman** [comment]
Please reopen if this is still an issue and you have some more details!
