### ISSUE TITLE
hardcoded path fkooman\Config\YamlFile

### ISSUE THREAD

**Issue by markuman** [fkooman/php-remote-storage#53]
Line 6 looks like a hardcoded path: https://github.com/fkooman/php-remote-storage/blob/master/bin/add-user.php#L6

It produced an error

    PHP Fatal error:  Uncaught Error: Class 'fkooman\Config\YamlFile' not found in /var/www/virtual/alva/html/php-remote-storage-1.0.5/bin/add-user.php:17

**Comment by fkooman** [comment]
Did you run [composer install](https://getcomposer.org/) before trying the `add-user.php` script? If you do not have Composer, you can also download the latest release [here](https://github.com/fkooman/php-remote-storage/releases), make sure you get the `tar.xz` file as that is an archive where I already ran `composer install`.
