### ISSUE TITLE
Log failed accesses

### ISSUE THREAD

**Issue by benrubson** [fkooman/php-remote-storage#54]
Hello,

Could it be possible to log failed accesses, for example with `log_error()` ?
Perhaps make this an option into `config/server.yaml` ?

Goal is to log a message each time a wrong user or password is used, or each time an unexpected (without good credentials / token) access to data is made.
`error_log("user $username: authentication failure in RemoteStorage");`

Goal is then to monitor these messages and ban malicious IPs, with for example Fail2Ban from a Linux server.

Thank you 👍 

Ben

**Comment by fkooman** [comment]
I've implemented logging to syslog for failed authentications, with the 'error' level. 

`php-remote-storage: invalid credentials for "foo"`

Is this what you had in mind? I'll create a new release if this is acceptable :-)

**Comment by benrubson** [comment]
Wow thank you very much for your work François !

What I have in mind is to have messages in HTTP server (Apache) log file when there are
- failed authentications ;
- failed data accesses (wrong credentials / tokens).

For example, with Basic Auth, we have the following messages produced :
```
[Sun Dec 18 11:50:34 2016] [error] [client 1.2.3.4] user bob not found: /pass/
[Sun Dec 18 11:50:42 2016] [error] [client 1.2.3.4] user alice: authentication failure for "/pass/": Password Mismatch
```

What is strange is that with your commit, sounds like you finally simply replace `error_log` (line 169) by syslog.
`error_log` would have been OK as we would then have messages in HTTP server error log.
But I made some tests (before opening this issue) and did not see any message in error log making wrong authentications.
I put some "debugging" `error_log` entries in `web/index.php` and clearly saw them.

Perhaps I missed something ? :)

Many thanks 👍

**Comment by fkooman** [comment]
Alright, I forgot to add logging when the `access_token` is wrong. Will add that later. 

The thing is with the logging, it depend on how you deploy php-remote-storage. If you are using e.g. Apache with mod_php the errors will show in the Apache log, if you are using php-fpm the errors will show in the php-fpm log when using `error_log()`. If you use syslog, no matter how you run php-remote-storage they will always end up in syslog[*]. I'd prefer to use a 'generic' log, like syslog, as that will also allow to log to remote systems etc and won't be depending on the web server you happened to be using.

So, with my commit you will see the errors in syslog (see journalctl, or `/var/log/messages` or similar).

[*] it seems when running the PHP built in server, syslog will appear in the console where you started the built in server, which is also kinda nice!

**Comment by benrubson** [comment]
Thank you again François for your feedback.

Could we then have the choice, through an option in server.yaml for example, between `error_log` and `syslog` please ? On some servers, `error_log` is preferable over `syslog`.

Just to know, in the current version, should I already get error messages for failed authentications ?
I do not manage to get them :)

And, finally, regarding error message patterns.
Would be nice if they could follow the [Fail2Ban regex](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/apache-auth.conf).
We would then not have to add specific regex.
So, for example :
```
user bob not found: php-remote-storage
user bob: authentication failure for "php-remote-storage": Password Mismatch
client used wrong authentication scheme: unknown access_token from php-remote-storage
```

Many thanks again 👍

**Comment by fkooman** [comment]
> Could we then have the choice, through an option in server.yaml for example, between error_log and syslog please ? On some servers, error_log is preferable over syslog.

I'm not a big fan of choice in this regard, I'd rather have one, which does not necessarily need to be `syslog`, but  on which servers is `error_log` preferable? I'm pretty sure Windows doesn't work anyway ;)

> Just to know, in the current version, should I already get error messages for failed authentications ?
I do not manage to get them :)

Only the `master` branch, not in a tagged released.

Regarding fail2ban, they are very Apache specific the ones you link to? Are you sure it could work? Would it make sense to create separate ones for just php-remote-storage (that then use syslog?) It seems fail2ban can also do stuff with syslog!

**Comment by benrubson** [comment]
> I'm not a big fan of choice in this regard, I'd rather have one, which does not necessarily need to be syslog, but on which servers is error_log preferable? I'm pretty sure Windows doesn't work anyway ;)

If we choose `error_log` and Apache `ErrorLog` [is set to use syslog](https://httpd.apache.org/docs/2.4/mod/core.html#errorlog), error message will go to syslog.
If it is set to a file, error messages will go to a file :)
Don't know for Nginx, but should be the same.
On some shared environments, where users have quite restricted PHP configuration, `error_log` is allowed but `syslog` is disabled.
`error_log` can then send to both syslog and files, depending on the server configuration.
Seems nicer (to me at least :)

> Regarding fail2ban, they are very Apache specific the ones you link to? Are you sure it could work?

Yes, if Fail2Ban has the Apache rules enabled, it then will work.
If Apache rules are not enabled, because for example you don't use Apache, you'll have to add matching rules to another ruleset, for example to the [Nginx one](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/nginx-http-auth.conf).
Sounds like it will be hard to find patterns which would match both Apache & Nginx rulesets :)
But we could have something slightly better with the following if you prefer (and it's nicer :) :
```
user "bob": was not found: "php-remote-storage"
user "bob": password mismatch: "php-remote-storage"
client used wrong authentication scheme: "php-remote-storage" unknown access_token
```
Very small modification needed to the existing Nginx ruleset to match the 2 first rules.
For the unknown access_token, a new rule would have to be added.

> Would it make sense to create separate ones for just php-remote-storage (that then use syslog?) It seems fail2ban can also do stuff with syslog!

Goal would be to avoid having to create a new ruleset for every new web application deployed.
It's better if applications can use some "template" messages, so that needed rules are already in production. It also avoid having too many rules.

**Comment by fkooman** [comment]
Working on it! 

There is one more problem, IP addresses do not get logged? Do you have any other means to obtain those?

**Comment by fkooman** [comment]
`master` is now using monolog with the ErrorLogHandler, so that should be taken care of, the only thing that's not taken care of is the format for fail2ban. 

To be fair: if hoster doesn't let you access syslog, I'm also pretty sure they won't allow you to modify the firewall of a host...

**Comment by benrubson** [comment]
> Working on it!

Thank you very much !

> There is one more problem, IP addresses do not get logged? Do you have any other means to obtain those?

They are automatically added before the message given to `error_log` by Apache (after by Nginx I think) :)

**Comment by benrubson** [comment]
> `master` is now using monolog with the ErrorLogHandler, so that should be taken care of.

Thank you !
Technically, by which line should messages been triggered ?
line 168 ? `$logger->info(` (only for development mode)
or line 177 ? `$logger->error(` (only in case of exception)

> the only thing that's not taken care of is the format for fail2ban.

What do you plan regarding this point ?

Thank you again !

**Comment by fkooman** [comment]
They are actually triggered in the components for verifying the login and bearer tokens:

https://github.com/fkooman/php-lib-rest-plugin-authentication-form/blob/ff72a429818c5650d85e89dec0366bdd961b9285/src/fkooman/Rest/Plugin/Authentication/Form/FormAuthentication.php#L100
https://github.com/fkooman/php-lib-rest-plugin-authentication-bearer/blob/45be75b251b230325cbfa0ecbf19ccfa522798fa/src/fkooman/Rest/Plugin/Authentication/Bearer/BearerAuthentication.php#L80

**Comment by fkooman** [comment]
> What do you plan regarding this point ?

Not sure yet, do you have any examples of other web applications, e.g. Wordpress or Drupal that implement this? I could look at their approach...

**Comment by fkooman** [comment]
would it be possible to just ship a 'fail2ban' policy with php-remote-storage? maybe you can make a start and I'll keep it updated for new releases...

**Comment by benrubson** [comment]
> They are actually triggered in the components for verifying the login and bearer tokens: (...)

OK, so we might simply edit them manually after having installed the application so that they match existing rules.
Not to forget after updates !

> do you have any examples of other web applications, e.g. Wordpress or Drupal that implement this?

Unfortunately no :/
Not sure there is a common way to manage this. Unfortunately.
This is why trying to match existing messages / rules seems to be a good starting point :)

> would it be possible to just ship a 'fail2ban' policy with php-remote-storage?

Quite difficult as it will depends on the server run (Apache, Nginx, ...).
As you can see, for example, [Apache regex rules](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/apache-auth.conf) and [Nginx regex rules](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/nginx-http-auth.conf) constructions are quite different. Only the message from the application itself (password mismatch / not found...) could be the same.

Perhaps in an effort of standardizing messages, we could go with the following ?
```
user "bob" not found: php-remote-storage
user "bob" password mismatch: php-remote-storage
client used invalid token: php-remote-storage
```

I plan to submit a PR to Fail2Ban project so that Apache & Nginx will match them by default (only minor modifications required to their ruleset).

What do you think about this ?

Thank you 👍

**Comment by benrubson** [comment]
So @fkooman as you can see [here](https://github.com/fail2ban/fail2ban/issues/1642) I'm pushing a set of default messages which could be used in web apps, such as php-remote-storage.

Here is the proposed rule :
`user \S* ?(not found|not authorized|password mismatch|sent invalid token|misbehaved): .+`

Perhaps we could then use it to format messages ?

Many thanks 👍

**Comment by fkooman** [comment]
I will look into this before the 2.0.0 release that will happen sometime soon I hope :)

**Comment by benrubson** [comment]
_Closing this for now._
