### ISSUE TITLE
 web/index.php does not run. Error reported.

### ISSUE THREAD

**Issue by technoboi** [fkooman/php-remote-storage#57]
web/index.php does not run. PHP tested with phpinfo() - works OK. php-remote-storage version 1.05. Running on php7.0 
When error reporting is switched on in web/index.php get this error:

Fatal error: Uncaught Error: Call to undefined function fkooman\Http\mb_strpos() in /var/www/php-remote-storage/vendor/fkooman/http/src/fkooman/Http/Url.php:224 Stack trace: #0 /var/www/php-remote-storage/web/index.php(89): fkooman\Http\Url->getRoot() #1 {main} thrown in /var/www/php-remote-storage/vendor/fkooman/http/src/fkooman/Http/Url.php on line 224

**Comment by fkooman** [comment]
Did you install the php mbstring module?

**Comment by technoboi** [comment]
Thank you for your reply. 
I am running Ubuntu so I did not install php-mbstring because that was listed for install under Fedora only in php-remote-storage/SERVER.md installation instructions.
However, I have now installed it, followed by 
sudo systemctl daemon-reloadsudo service apache2 restart

That took me further. I was presented with a login screen. I logged in but then encountered:ERROR: SQLSTATE[HY000]: General error: 1 no such table: approval

**Comment by fkooman** [comment]
Hmm.. I think the data directory must be writable also:
```
$ sudo mkdir data
$ sudo chown www-data.www-data data
```

**Comment by technoboi** [comment]
That is what I have already.
drwxr-xr-x  4 www-data www-data  4096 Apr 13 21:53 dataHowever, I wasn't sure where in the directory structure to place it. 
It is currently in 
php-remote-storage/
I tried increasing the permissions but that made no difference - so maybe I have placed it in the wrong directory?

**Comment by fkooman** [comment]
no, that should be correct under the php-remote-storage directory. At some point when I was testing stuff, this did work on Ubuntu/Debian, but to be honest that was some time back already! I have no idea what is going on then, the DB was not initialized, but it should have been done automatically when you open php-remote-storage in your browser...

**Comment by technoboi** [comment]
Contents of data/-rw-r--r-- 1 www-data www-data    0 Apr 13 21:53 rs.sqlite
drwxr-x--- 2 www-data www-data 4096 Apr 13 21:53 storage
drwx------ 7 www-data www-data 4096 Apr 14 20:25 tpl

I had to become root to cd into data/storage (no content) and data/tplIn data/tpldrwxr-xr-x 2 www-data www-data 4096 Apr 14 20:24 0fdrwxr-xr-x 2 www-data www-data 4096 Apr 14 20:24 5e
drwxr-xr-x 2 www-data www-data 4096 Apr 14 20:24 77
drwxr-xr-x 2 www-data www-data 4096 Apr 14 20:25 f2
drwxr-xr-x 2 www-data www-data 4096 Apr 14 20:24 f8
in data/tpl/0f-rw-r--r-- 1 www-data www-data 2494 Apr 14 20:24 0f3bb40e5debf94b131cb8e9b4ec15f9748508e9913033ef50da639a7e66c5e5.phpthe content of 5e,77,f2 & f8 were similar to datatpl/0f

So something has been stored.

**Comment by fkooman** [comment]
Ah!  remove the DB file, i think that may solve it, it probably only initialized it when the file is not yet there! 
The tpl files are template cache.

**Comment by fkooman** [comment]
With DB file I mean `rs.sqlite`.

**Comment by technoboi** [comment]
Many thanks! That was it. 
I'll try it out tomorrow. I'm hoping to use it to store Laverna notes. I intend to  to write some PHP to convert my Tomboy notes to Laverna notes as I've found no existing software to do that.

Thanks again :-)

**Comment by fkooman** [comment]
See #58 for a proposed fix, I also updated the documentation to indicate you need `php5-mbstring` on Debian/Ubuntu.

**Comment by technoboi** [comment]
I think I would add that the solution, regarding the sqlite database,  is to delete the 0B sqlite file. Also, this is a solution for an error AFTER login, that was the second error I experienced, whereas the original problem I had was there was no login screen. That problem was solved by the installation of php5-mbstring.
