### ISSUE TITLE
ERROR: Could Not Find Driver

### ISSUE THREAD

**Issue by techiem2** [fkooman/php-remote-storage#60]
I'm working on getting it setup on a Debian 8 VPS.  As far as I can tell I have all the requirements installed, but when I access it I get "ERROR: Could Not Find Driver".
The Apache log file just says the same thing.

Any ideas what I might be missing still?

**Comment by fkooman** [comment]
Maybe this is related to PDO / SQlite support? That's my first guess...

**Comment by fkooman** [comment]
$ php -i | grep -i sqlite
/etc/php.d/20-sqlite3.ini,
/etc/php.d/30-pdo_sqlite.ini,
PDO drivers => sqlite
pdo_sqlite
PDO Driver for SQLite 3.x => enabled
SQLite Library => 3.20.1
sqlite3
SQLite3 support => enabled
SQLite3 module version => 7.1.8
SQLite Library => 3.20.1
sqlite3.extension_dir => no value => no value

$ php -i | grep -i pdo
/etc/php.d/20-pdo.ini,
/etc/php.d/30-pdo_sqlite.ini,
PDO
PDO support => enabled
PDO drivers => sqlite
pdo_sqlite
PDO Driver for SQLite 3.x => enabled

**Comment by techiem2** [comment]
Looks pretty close to what I have: 

```
# php -i | grep -i sqlite
/etc/php5/cli/conf.d/20-pdo_sqlite.ini,
/etc/php5/cli/conf.d/20-sqlite3.ini,
PDO drivers => mysql, sqlite
pdo_sqlite
PDO Driver for SQLite 3.x => enabled
SQLite Library => 3.8.7.1
sqlite3
SQLite3 support => enabled
SQLite3 module version => 0.7-dev
SQLite Library => 3.8.7.1
sqlite3.extension_dir => no value => no value

#  php -i | grep -i pdo
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-pdo_mysql.ini,
/etc/php5/cli/conf.d/20-pdo_sqlite.ini,
API Extensions => mysql,mysqli,pdo_mysql
PDO
PDO support => enabled
PDO drivers => mysql, sqlite
pdo_mysql
PDO Driver for MySQL => enabled
pdo_mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock
pdo_sqlite
PDO Driver for SQLite 3.x => enabled
```

**Comment by D4nte** [comment]
I had the same issue and I just needed to install php-sqlite3 package on ubuntu.
I suggest to add this step to the readme install.
