### ISSUE TITLE
Installation of the Server Add-user error

### ISSUE THREAD

**Issue by nukedone** [fkooman/php-remote-storage#61]
I experience the issues with adding the user in the initial stages of the setup.
The error says 

`require_once(): Failed opening required '/var/www/php-remote-storage/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/php-remote-storage/bin/add-user.php on line 4`

I guess that some additional framework is missing and should be located in the /vendor dir.

What is it?

**Comment by fkooman** [comment]
You forgot to run `composer install`, I guess you are using the Git checkout and not the release tarball :)

**Comment by fkooman** [comment]
I'm not sure the `master` branch is actually working. For something that works please use the last released version, 1.0.5.

**Comment by nukedone** [comment]
@fkooman Thank you for the quick response!
I saw the problem and downloaded the tarball 1.0.5
I created a user and proceeded next
My setup is in the virtual machine which has bridged IP to the LAN network
I am trying to connect from the host and and a mobile phone in the LAN subnet.
When I enter the username@192.168.1.150 in the Laverna remotestorage connection, it does nothing. I guess I am doing something wrong.
Don't know what!
Thank you again for the quick response!

**Comment by fkooman** [comment]
did you follow all installation [instructions](https://github.com/fkooman/php-remote-storage/blob/master/SERVER.md)? You need to have HTTPS and DNS working I think, could be self signed as well.

**Comment by nukedone** [comment]
Yes, I am able to successfully, from the host machine, open the 192.168.1.150. I accepted the selfsigned certificate. But still no connection from laverna's setup.
Is therea any way to post some log to see what's happening?
Thanks, @fkooman !

**Comment by nukedone** [comment]
I am making progress. It is default apache sites that I have disabled. Not I get the message Unable to find driver!

**Comment by nukedone** [comment]
I follow the otehr post:
my
`sudo php -i | grep -i sqlite` gives 
`/etc/php/5.6/cli/conf.d/20-pdo_sqlite.ini,
/etc/php/5.6/cli/conf.d/20-sqlite3.ini,
PDO drivers => sqlite
pdo_sqlite
PDO Driver for SQLite 3.x => enabled
SQLite Library => 3.11.0
sqlite3
SQLite3 support => enabled
SQLite3 module version => 0.7-dev
SQLite Library => 3.11.0
sqlite3.extension_dir => no value => no value`

I am on Mint 18.2 which has php7 as default. I added the php5.6 from a ppa.

**Comment by nukedone** [comment]
I closed it because it refers to  [https://github.com/fkooman/php-remote-storage/issues/60](#60)

**Comment by fkooman** [comment]
Why would you downgrade PHP? And maybe the configuration for the CLI is not the same was the one for php-fpm or mod_php...

**Comment by nukedone** [comment]
I tried to level with the setups. :/

**Comment by nukedone** [comment]
I wen't back to php7.0. Now I am getting Error 500.

**Comment by nukedone** [comment]
I enabled the php error log and nothing in `/var/log/apache2/error.log`

**Comment by nukedone** [comment]
I managed to work up the setup
I am getting the remotestorage site
However, when I log in it says
`ERROR: SQLSTATE[HY000]: General error: 1 no such table: approval`

**Comment by nukedone** [comment]
the 500 error was due to disabled php7.0 mod

`sudo a2enmod php7.0`

**Comment by fkooman** [comment]
The table approval missing is probably due to an existing sqlite file of size 0 bytes in the data dir, if you remove this file it should work!

**Comment by nukedone** [comment]
As you said! the error is gone!
Still impossible to log in with Laverna.

**Comment by fkooman** [comment]
What is the error you see in your javascript console?

**Comment by nukedone** [comment]
I am using the desktop version of Laverna. Can't debug it.

**Comment by fkooman** [comment]
Well, that's a bit of a problem then... Not sure how to help you there? Can you try any other application? For example https://webmarks.5apps.com/ ?

**Comment by nukedone** [comment]
I went to the site and authenticated and the application was approved successfully

**Comment by nukedone** [comment]
I am trying to build the Laverna from the github master brach.
I ran upon an issue [https://github.com/Laverna/laverna-desktop/issues/3](url)
