### ISSUE TITLE
secookie dependency fails to download

### ISSUE THREAD

**Issue by bahf** [fkooman/php-remote-storage#64]
Output from composer.phar:
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 35 installs, 0 updates, 0 removals
  - Installing fkooman/secookie (2.0.0): Downloading (connecting...) ~ Downloading (failed)       ~    Failed to download fkooman/secookie from dist: The "https://api.github.com/repos/fkooman/php-secookie/zipball/ece8801d9987f4b58889e001a63929b0c6546cf1" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing fkooman/secookie (2.0.0): Cloning ece8801d99

                                                                                                   
  [RuntimeException]                                                                               
  Failed to clone https://github.com/fkooman/php-secookie.git via https, ssh protocols, aborting.  
                                                                                                   
  - https://github.com/fkooman/php-secookie.git                                                    
    Cloning into '/opt/xeb/php-remote-storage/vendor/fkooman/secookie'...                          
    remote: Invalid username or password.                                                          
    fatal: Authentication failed for 'https://github.com/fkooman/php-secookie.git/'                
                                                                                                   
  - git@github.com:fkooman/php-secookie.git                                                        
    Cloning into '/opt/xeb/php-remote-storage/vendor/fkooman/secookie'...                          
    git@github.com: Permission denied (publickey).                                                 
    fatal: Could not read from remote repository.                                                  
                                                                                                   
    Please make sure you have the correct access rights                                            
    and the repository exists.

**Comment by fkooman** [comment]
can you try `composer update` instead of `composer install`?

**Comment by fkooman** [comment]
https://github.com/fkooman/php-remote-storage/commit/d39ef67fb7b076c416a7de40c712a49f81c865d9
