### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by muralikodali** [fkooman/php-remote-storage#65]
i have got following display when tried to sign in:
**The requested URL /php-remote-storage/web/_account was not found on this server.**

**Comment by fkooman** [comment]
Please follow the instructions [here](https://github.com/fkooman/php-remote-storage/blob/master/SERVER.md).

**Comment by muralikodali** [comment]
thanks for your reply.

need to follow documentation **carefully**:

**This document will assume you use the name storage.local for your server. If you have your own domain name you can use that instead. These instructions configure the storage server on its own domain, as that is required for making WebFinger work without hackery.**
