### ISSUE TITLE
No CORS info in Apache 304 responses

### ISSUE THREAD

**Issue by benrubson** [fkooman/php-remote-storage#67]
Hi,

This follows https://github.com/skddc/webmarks/issues/67.

I'm facing the following issue where 304 Apache responses do not include CORS info :
https://bz.apache.org/bugzilla/show_bug.cgi?id=51223

I use [Webmarks](https://github.com/skddc/webmarks) with PHP remoteStorage.

Due to this "bug", Webmarks disconnects quickly :
![screen shot 2018-11-03 at 10 12 15](https://user-images.githubusercontent.com/6764151/47950358-5ec34280-df51-11e8-96b5-73d8ff33ca94.png)

Is there any workaround ?
Perhaps requests leading to 304 answers could be avoided / replaced by requests leading to 200 answers (but this could perhaps generate more traffic) ?

Thank you 👍 

Ben

**Comment by fkooman** [comment]
Ah this issue again! Interesting it is still not resolved one way or the other...

My concern is that it would break (other) things if I modify it in any way, I haven't been using remoteStorage for quite some time now, so I'm not really up-to-date on what's going on in the various project(s)...

If you are able to provide a (tested) patch, maybe it can be applied. What do you think?

**Comment by fkooman** [comment]
See also https://bz.apache.org/bugzilla/show_bug.cgi?id=61820#c3

**Comment by skddc** [comment]
> so I'm not really up-to-date on what's going on in the various project(s)

There's nothing going on that would have changed anything around 304s or how they're handled. As the protocol is working as intended, aside from improving clarity here and there, a few people just started [trying to add resumable/large file uploads](https://community.remotestorage.io/t/resumable-file-uploads/461).

**Comment by benrubson** [comment]
> See also https://bz.apache.org/bugzilla/show_bug.cgi?id=61820#c3

So according to Roy T. Fielding there, I understand that this should be corrected at Apache level.
Fingers crossed for an upcoming patch.

I then close this, thank you for your feedbacks @fkooman & @skddc 👍

**Comment by rosano** [comment]
Just wondering if anyone found a workaround for this? I didn't know it was an Apache issue, was pulling out my proverbial hair. I tried simply changing the response code to 200 but it still seems to behave the same way. Apparently they are having a discussion 'soon'.

**Comment by skddc** [comment]
> Apparently they are having a discussion 'soon'.

Could you elaborate on this? I'm trying to find information about the current state of [that issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=51223).

**Comment by rosano** [comment]
@skddc I read that in the last comment from the bug report page https://bz.apache.org/bugzilla/show_bug.cgi?id=61820#c12

**Comment by skddc** [comment]
Ah, thanks. I didn't realize there was a second bug open, with actual discussion.
