### ISSUE TITLE
Composer install failing

### ISSUE THREAD

**Issue by raucao** [fkooman/php-remote-storage#73]
I was just going to verify the fix in #68 (and finish my Ubuntu installation howto), but I ran into one of the PHP package dependencies telling me that it needs authentication:

```plain
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 36 installs, 0 updates, 0 removals
  - Installing fkooman/secookie (2.0.1):     Authentication required (git.tuxed.net):
```

I tried to see what's on `git.tuxed.net` in general, but the whole site seems to have gone offline. So I assume the authentication request is actually just a side effect of the package repo being down at the moment.

**Comment by fkooman** [comment]
Composer runs fine now, but I am having some trouble getting the test suite to run with PHP 8, would require some more fixes it seems...

**Comment by fkooman** [comment]
Updated a lot of other stuff in the meantime, it is a miracle it still works, also with PHP 8 now...

**Comment by raucao** [comment]
Nice! :)
