### ISSUE TITLE
401 responses are missing CORS headers

### ISSUE THREAD

**Issue by raucao** [fkooman/php-remote-storage#74]
I revoked a token:

![Screenshot from 2022-01-21 17-25-43](https://user-images.githubusercontent.com/842/150612778-4d33e75d-603f-45ef-adfb-a17117845380.png)

**Comment by fkooman** [comment]
I don't see that when testing on localhost, but perhaps there's an exception for CORS on localhost? has been years since I looked at this :)

**Comment by raucao** [comment]
Want access to that testing VM to check it out there?

**Comment by fkooman** [comment]
That won't be necessary. It looks like in the `master` branch this was never properly implemented... :)

Perhaps it would be easier to take 1.0.5 and update it for modern PHP...

**Comment by raucao** [comment]
Hmm...

>  93 commits to master since this release

The rest seems to be working just fine on my test deployment. I'd say it's worth it to add the headers to those responses and perhaps tag `1.0.6` then?

**Comment by fkooman** [comment]
> The` rest seems to be working just fine on my test deployment. I'd say it's worth it to add the headers to those responses and perhaps tag 1.0.6 then?

Might be enough yeah, not sure! Do you still have your 'generic' test script to test RS servers?

**Comment by raucao** [comment]
Yup: https://github.com/remotestorage/api-test-suite

Was going to run it against that server actually.

**Comment by fkooman** [comment]
It might need more CORS response headers I guess?

**Comment by raucao** [comment]
Working nicely. The widget will ask you to re-auth the app upon seeing the 401 now. :+1:
