### ISSUE TITLE
Login throws exception

### ISSUE THREAD

**Issue by raucao** [fkooman/php-remote-storage#76]
After pulling the latest commits, I got this exception when signing in to my account:

    PHP Fatal error:  Uncaught Error: Call to a member function isOkay() on string in /var/www/php-remote-storage/web/index.php:54\nStack trace:\n#0 {main}
    thrown in /var/www/php-remote-storage/web/index.php on line 54

It seems to have been introduced with 9371a87.

**Comment by fkooman** [comment]
Thanks! Didn't run into this problem before with PHP's internal web server.
