### ISSUE TITLE
support resumable upload/progress

### ISSUE THREAD

**Issue by fkooman** [fkooman/php-remote-storage#9]
For example, http://www.resumablejs.com/

It includes server side modifications that we could support, also look at http://plupload.com/ to see if it is possible to share the same server side code somehow...

**Comment by fkooman** [comment]
I guess no one is really interested in it, at least not me to implement this. Needs to be part of the spec first afaic.

**Comment by skddc** [comment]
> Needs to be part of the spec first afaic.

That would be great!
